services:
    web:
        build: .
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - '3000:3000'
        working_dir: /app
        command: npm run dev -- --port 3000 --host

volumes:
    node_modules:
    